server_state: "DEBUG_SQL"
embedded_password: null
local_database:
  url: "jdbc:mysql://127.0.0.1/exilius?useSSL=false&serverTimezone=UTC"
  username: "exilius"
  password: "Crm561996!"
store_database: null
vote_database: null
hiscores_database: null